# Generated by Django 5.2.7 on 2025-10-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_title", models.CharField(max_length=150)),
                ("skill_icon", models.CharField(max_length=5000)),
                (
                    "skill_category",
                    models.CharField(
                        choices=[
                            ("DEF", "Defensive"),
                            ("ATK", "Attacking"),
                            ("PRO", "Programming"),
                            ("DSC", "Data science"),
                            ("AI", "Artificial Intelligence"),
                            ("T&T", "Tools & Technologies"),
                            ("OTS", "Others"),
                        ],
                        default="ATK",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
