# Generated by Django 5.2.7 on 2025-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="about",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_icon", models.CharField(max_length=5000)),
                ("name", models.CharField(max_length=150)),
                ("home_profession", models.CharField(max_length=5000)),
                ("home_Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="social_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_url", models.CharField(max_length=5000)),
                ("social_name", models.CharField(max_length=150)),
                ("social_icon", models.CharField(max_length=5000)),
            ],
        ),
    ]
