# Generated by Django 5.2.7 on 2025-10-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0003_rename_home_home_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_icon", models.CharField(max_length=150)),
                ("email_name", models.CharField(max_length=150)),
                ("email_address", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=13)),
            ],
        ),
    ]
