# Generated by Django 5.2.7 on 2025-10-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0007_alter_experiences_ex_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ach_logo", models.CharField(max_length=2000)),
                ("Ach_title", models.CharField(max_length=2000)),
                ("Ach_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Art_Background", models.CharField(max_length=2000)),
                ("Tra_title", models.CharField(max_length=2000)),
                ("Tra_description", models.TextField()),
                ("Tra_link", models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Provider_logo", models.CharField(max_length=2000)),
                ("Provider_name", models.CharField(max_length=2000)),
                ("Certifiate_name", models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Provider_logo", models.CharField(max_length=2000)),
                ("Provider", models.CharField(max_length=2000)),
                ("Time_duration", models.CharField(max_length=2000)),
                ("score", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Training_courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tra_logo", models.CharField(max_length=2000)),
                ("Tra_title", models.CharField(max_length=2000)),
                ("Tra_description", models.TextField()),
            ],
        ),
    ]
