# Generated by Django 5.2.7 on 2025-10-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0008_achievements_articles_certifications_education_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="Provider_logo",
            new_name="Provider_location",
        ),
    ]
