# Generated by Django 5.2.7 on 2025-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0011_medium"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=300)),
                ("subject", models.CharField(max_length=300)),
                ("message", models.TextField()),
            ],
        ),
    ]
