# Generated by Django 5.2.7 on 2025-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0017_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("message", models.CharField(max_length=2000)),
            ],
        ),
    ]
