# Generated by Django 5.2.7 on 2025-10-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0019_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="topskill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("skill_percent", models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name="experiences",
            name="Ex_for",
            field=models.CharField(
                choices=[
                    ("Company", "Company"),
                    ("Website", "Website"),
                    ("Institution", "Institution"),
                    ("School", "School"),
                    ("Competition", "Competition"),
                    ("CTF", "CTF"),
                    ("me", "me"),
                ],
                default="SC",
                max_length=20,
            ),
        ),
    ]
