# Generated by Django 5.2.7 on 2025-10-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0023_alter_skills_skill_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_deployed",
            new_name="project_img",
        ),
    ]
