# Generated by Django 5.2.7 on 2025-10-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0002_about_home_social_link"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="home",
            new_name="home_data",
        ),
    ]
