# Generated by Django 5.2.7 on 2025-10-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0004_email_location_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="location",
            name="location_name",
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=150)),
                ("project_github", models.CharField(max_length=2000)),
                ("project_deployed", models.CharField(max_length=2000)),
                ("project_description", models.TextField()),
                (
                    "project_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Data.language"
                    ),
                ),
            ],
        ),
    ]
