# Generated by Django 5.2.7 on 2025-10-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0005_language_alter_location_location_name_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ex_post", models.CharField(max_length=150)),
                (
                    "Ex_for",
                    models.CharField(
                        choices=[
                            ("CO", "Company"),
                            ("WB", "Website"),
                            ("IN", "Institution"),
                            ("SC", "School"),
                            ("CP", "Competition"),
                            ("CTF", "CTF"),
                            ("OTS", "Others"),
                        ],
                        default="SC",
                        max_length=20,
                    ),
                ),
                ("Ex_forname", models.CharField(max_length=150)),
                ("Ex_date", models.CharField(max_length=150)),
                ("Ex_works", models.TextField(max_length=2000)),
            ],
        ),
    ]
