# Generated by Django 5.2.7 on 2025-10-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0006_experiences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiences",
            name="Ex_for",
            field=models.CharField(
                choices=[
                    ("Company", "Company"),
                    ("Website", "Website"),
                    ("Institution", "Institution"),
                    ("School", "School"),
                    ("Competition", "Competition"),
                    ("CTF", "CTF"),
                    ("Others", "Others"),
                ],
                default="SC",
                max_length=20,
            ),
        ),
    ]
