# Generated by Django 5.2.7 on 2025-10-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0009_rename_provider_logo_education_provider_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="Provider",
            new_name="Title",
        ),
    ]
