# Generated by Django 5.2.7 on 2025-10-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0010_rename_provider_education_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="medium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mediumacc", models.CharField(max_length=2000)),
            ],
        ),
    ]
