# Generated by Django 5.2.7 on 2025-10-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0012_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="contact",
        ),
    ]
