# Generated by Django 5.2.7 on 2025-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0015_profileimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="birthday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday_date", models.CharField(max_length=2000)),
            ],
        ),
    ]
