# Generated by Django 5.2.7 on 2025-10-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0016_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_icon", models.CharField(max_length=2000)),
                ("work_title", models.CharField(max_length=2000)),
                ("work_description", models.CharField(max_length=2000)),
            ],
        ),
    ]
