# Generated by Django 5.2.7 on 2025-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0022_alter_skills_skill_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skill_category",
            field=models.CharField(
                choices=[
                    ("Defensive", "Defensive"),
                    ("Attacking", "Attacking"),
                    ("Programming", "Programming"),
                    ("Data_science", "Data science"),
                    ("Artificial_Intelligence", "Artificial Intelligence"),
                    ("Tools_and_Technologies", "Tools & Technologies"),
                    ("Others", "Others"),
                ],
                default="Defensive",
                max_length=200,
            ),
        ),
    ]
