# Generated by Django 5.2.7 on 2025-10-22 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0024_rename_project_deployed_project_project_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="Tra_date",
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
